<div class="meta-box-sortabless">
	<div id="wizard_page">
        <div class="postbox" id="sm_pnres">
            <h3 class="hndle"><span>About:</span></h3>
            <div class="inside">
                <a class="sm_button sm_pluginCommercial" href="https://wp.manticoresearch.com">Plugin Website</a>
                <a class="sm_button sm_pluginHome" href="https://wp.manticoresearch.com/blog/article/1">Plugin
                    Tutorial</a>
                <a class="sm_button sm_pluginSupport" href="http://wordpress.org/">Support Forum</a>
            </div>
        </div>
        <div class="postbox" id="sm_pnres">
            <h3 class="hndle"><span>Support:</span></h3>
            <div class="inside">
                <p>
                    Need help? <a target="_blank" href="https://wp.manticoresearch.com/support?access_key=<?=$this->view->devOptions['secure_key']?>">Contact us!</a>
                </p>
            </div>
        </div>
	</div>
</div>
</div>
</div>

