<?php echo $this->render('admin/messagebox.phtml'); ?>
<div class="postbox">
	<h3 class="hndle">Select manticore connection type</h3>
	<div class="inside">

        <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>" id="wizard_form">
            <input type="hidden" name="action" value="add_secure_key" />
            <p style="margin:0;">Add secure key <img class="j-hover-popup"
                                                     title="Secure key allow to use premium functionality"
                                                     src="<?php echo plugins_url( '../assets/img/question.png', __DIR__ ); ?>">
                <input style="margin-left: 20px;" type="text" name="secure_key" value=""
                       placeholder="Paste here your secure key">

                <input class="button-primary" type="button" name="next"
                       onClick="return wizard_next();" value="Next" />
                <input class="button-secondary cancel alignright" type="button"
                       onClick="return wizard_cancel();" value="Cancel Wizard" />
            </p>
        </form>
	</div>
</div>
